F/add custom event dialog
Joonpark13/serif.nu pull request #110
Opened 2019-11-18 04:36 UTC by albirdy98

<img width="406" alt="Screen Shot 2019-11-17 at 10 18 11 PM" src="https://user-images.githubusercontent.com/38387890/69024959-a1a05e80-098a-11ea-9f8a-2ffdc164dc0c.png">

restyled the custom event dialog

2019-11-18 05:11 UTC, kevinjihwanlee requested changes
See comments! Don't forget to write tests.

2019-11-18 05:11 UTC, kevinjihwanlee commented on src/components/sidebar/custom/Custom.js
> +import React, { Fragment } from 'react';
Is there a particular reason why you're using two separate files for this?

2019-11-18 05:11 UTC, kevinjihwanlee commented on src/components/sidebar/custom/CustomDialog.js
> +import React, { useState, Fragment } from 'react';
This shouldn't be called a dialog since it just resides in a tab now. Maybe call it `CustomEventForm` or something.

2019-11-18 05:11 UTC, kevinjihwanlee commented on src/components/sidebar/custom/CustomDialog.js
> +      <form noValidate autoComplete="off">
I think I was unclear in the ticket description - we won't actually need a `form` element for this. What we can do is construct a state (similar to how you have the day of the week right now), and upon clicking of the submit button later, dispatch an action that alters the Redux store state. We can talk more on Slack if this is confusing.

2019-11-18 05:11 UTC, kevinjihwanlee commented on src/components/sidebar/custom/CustomDialog.js
> +      <form noValidate autoComplete="off">
Actually, scratch what I said - a form is good, but we don't need the vanilla HTML `form` element, we can stick everything under the `FormControl` like you have below. is there a reason why these two first `TextFields` are outside of the `FormControl`?

2019-11-18 05:11 UTC, kevinjihwanlee commented on src/components/sidebar/custom/CustomDialog.js
> +        <Button>Create</Button>
What's the difference between Create and Save?

2020-02-20 02:52 UTC, amyanchen commented
Used material UI css instead of custom classes and moved `TextFields` and `Button` into `FormControl`

![image](https://user-images.githubusercontent.com/33207871/74896391-c6291f80-5359-11ea-8da0-a71eacfaf2e0.png)

2020-02-26 20:46 UTC, kevinjihwanlee approved these changes
looks good to me!

2020-02-26 21:38 UTC, merged