Create browse tab
Joonpark13/serif.nu pull request #13
Opened 2018-10-27 17:21 UTC by kevinjihwanlee

2018-10-27 17:22 UTC, kevinjihwanlee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create browse tab](https://trello.com/c/3JpzjVob/27-create-browse-tab)

2018-10-27 18:03 UTC, Joonpark13 requested changes

2018-10-27 18:03 UTC, Joonpark13 commented on src/components/Sidebar/SidebarView.js
> +      value: 0,
Let's use more descriptive values as shown in the example here: https://material-ui.com/demos/tabs/#wrapped-labels

2018-10-27 19:46 UTC, Joonpark13 commented on src/components/Sidebar/SidebarView.js
> +          <Tab label="Search" />
Getting console errors when I fire up the branch, I think it's because you didn't add the values to the Tab components themselves.

2018-10-27 19:46 UTC, Joonpark13 commented on src/components/Sidebar/SidebarView.js
> +          <Tab label="Search" />
Don't forget to test out any changes you make locally before you push them up, no matter how small the change!

2018-10-30 01:38 UTC, Joonpark13 approved these changes

2018-10-30 01:39 UTC, Joonpark13 commented
When you rebase, you'll find that there's extra space on the bottom again, just like for #12 . Make sure you fix that, but after that you're good to squash & merge.

2018-10-30 02:58 UTC, merged