Format sections list
Joonpark13/serif.nu pull request #17
Opened 2018-11-02 15:18 UTC by kevinjihwanlee

2018-11-02 15:19 UTC, kevinjihwanlee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Format sections list](https://trello.com/c/GXnwmdtC/32-format-sections-list)

2018-11-02 15:19 UTC, kevinjihwanlee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Format sections list](https://trello.com/c/GXnwmdtC/32-format-sections-list)

2018-11-03 02:16 UTC, Joonpark13 requested changes

2018-11-03 02:16 UTC, Joonpark13 commented on src/components/Sidebar/SectionSelection.js
> +              <Typography>{section.instructor.map((t, i) => (`${t}${i !== section.instructor.length - 1 ? ', ' : ''}`))}</Typography>
Let's try to avoid use of single letter variables names. We can definitely be descriptive AND concise.

2018-11-03 02:16 UTC, Joonpark13 commented on src/components/Sidebar/SectionSelection.js
> +              <Typography>{section.instructor.map((t, i) => (`${t}${i !== section.instructor.length - 1 ? ', ' : ''}`))}</Typography>
Also I feel like the length of this line should throw a linting error?

2018-11-03 02:16 UTC, Joonpark13 commented on src/components/Sidebar/SectionSelection.js
> +              <Typography>{section.instructor.map((t, i) => (`${t}${i !== section.instructor.length - 1 ? ', ' : ''}`))}</Typography>
Tests are also failing because we're missing coverage on this line

2018-11-04 05:15 UTC, Joonpark13 commented
Not a big deal this time since I pulled down and looked, but a reminder that with PRs that contain visual changes, screenshots are much appreciated!

2018-11-04 05:18 UTC, Joonpark13 commented
Looks good visually, but there's a console error when I click on a course to show sections. Can you address that?

2018-11-04 05:32 UTC, kevinjihwanlee commented
<img width="276" alt="screenshot 2018-11-04 00 31 37" src="https://user-images.githubusercontent.com/13278696/47960403-265f4b00-dfc9-11e8-9e42-107cb1cbdb10.png">

2018-11-04 05:41 UTC, Joonpark13 approved these changes

2018-11-04 06:24 UTC, merged