Implement browse schools
Joonpark13/serif.nu pull request #23
Opened 2018-11-21 02:29 UTC by kevinjihwanlee

2018-11-21 02:32 UTC, kevinjihwanlee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement browse schools](https://trello.com/c/tjNYggL4/50-implement-browse-schools)

2018-11-25 18:40 UTC, Joonpark13 requested changes

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +    this.fetchSchools = props.fetchSchools;
You rarely ever want to set state using props. Here, there's no need to set any state - you don't even need a constructor. Just use the props themselves in the render & lifecycle method.

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +    this.fetchSchools();
just call the prop function

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +          <Grid item md={9} sm={12} xs={12} className={this.classes.calendar}>
just use the `classes` prop

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +export default connect(null, mapDispatchToProps)(toJS(withStyles(styles)(App)));
Just for clarity's sake, can you break this out into two lines?
`const AppWithStyles = withStyles(styles)(App);`
`export default connect(null, mapDispatchToProps)(AppWithStyles);`

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.test.js
> +    const wrapper = shallow(<UnstyledApp classes={classes} fetchSchools={dummyFunction} />);
You can just give it an empty anonymous function: `() => {}`

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +export const mapDispatchToProps = dispatch => ({
Put the mapDispatchToProps at the bottom of the file, just before the `export`s to follow convention.

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +  fetchSchools: () => {
You can use [shorthand notation](https://egghead.io/lessons/javascript-redux-using-mapdispatchtoprops-shorthand-notation) for this.

2018-11-25 18:40 UTC, Joonpark13 commented on src/components/App.js
> +    this.fetchSchools = props.fetchSchools;
This will also fix your coverage issue.

2018-12-02 14:44 UTC, Joonpark13 commented on src/components/App.js
> +  fetchSchools: () => {
```javascript
const mapDispatchToProps = {
  fetchSchools,
};
```

2019-01-19 22:08 UTC, Joonpark13 approved these changes

2019-01-19 22:30 UTC, merged