Move selectors into their own directory
Joonpark13/serif.nu pull request #78
Opened 2019-05-30 18:35 UTC by amyanchen

Previously, selectors lived in the container files they were used in. Now, they all live in the selectors directory, along with their corresponding tests.

2019-05-30 18:36 UTC, amyanchen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Move selectors into their own directory](https://trello.com/c/IvFg0oN6/72-move-selectors-into-their-own-directory)

2019-05-30 19:25 UTC, Joonpark13 requested changes

2019-05-30 19:25 UTC, Joonpark13 commented on src/selectors/index.js
> +import { meetsDuringDow, meetsDuringHour } from 'components/calendar/calendar-helpers';
Now that these are being used outside of components, let's put these in `util/time` instead and import them from there.

2019-05-30 19:25 UTC, Joonpark13 commented on src/selectors/index.js
> +
Can we move all of the helper functions to the top, then order the selectors below that by top level store fields? Like all the `search` selectors, then all the `browse` selectors, etc.

2019-05-30 19:25 UTC, Joonpark13 commented on src/selectors/index.js
> +
Wouldn't hurt to delineate each of the three using comments either (see action-types.js)

2019-05-30 21:57 UTC, Joonpark13 requested changes

2019-05-30 21:57 UTC, Joonpark13 commented on src/selectors/index.js
> +export function scheduledSectionsSelector(state) {
This should be `schedule` not `scheduled`

2019-05-30 21:57 UTC, Joonpark13 commented on src/selectors/index.js
> +/* schedule */
No need for this to be a multi line comment. Can we make this `// Schedule` instead? (Same with browse and search)

2019-05-30 21:59 UTC, Joonpark13 commented
Also seeing a console error on load - can you look into that? Make sure you manually load up and test the app for your PRs!

2019-06-05 22:01 UTC, Joonpark13 commented
The console error on load is gone but now it errors out when you add a class.

2019-06-05 22:49 UTC, Joonpark13 approved these changes

2019-06-05 22:54 UTC, Joonpark13 requested changes
Oh I just noticed you have commits under `images` - not sure how you got that in there but don't think we need those.

2019-06-05 23:23 UTC, Joonpark13 approved these changes

2019-06-28 02:57 UTC, merged